jobs:
  some-name:
    runs-on: some-os
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.4
        with:
          version: # wstaw odpowiednią wersję Poetry
          virtualenvs-create: # opcjonalne, domyślnie true
          virtualenvs-in-project: # opcjonalne, domyślnie false
          virtualenvs-path: # opcjonalne, domyślnie {cache-dir}/virtualenvs
          installer-parallel: # opcjonalne, domyślnie true
          installation-arguments: # opcjonalne
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
